CREATE DATABASE IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS userInfos;

CREATE TABLE test.userInfos (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nom VARCHAR(45) NOT NULL DEFAULT '',
  Prenom VARCHAR(45) NOT NULL DEFAULT '',
  Adresse VARCHAR(255) NOT NULL DEFAULT '',
  Birthdate DATE NOT NULL,
  Phone VARCHAR(11) NOT NULL DEFAULT '',
  Mail VARCHAR(89) NOT NULL DEFAULT '',
  NumSecu VARCHAR(16) NOT NULL DEFAULT '',

  PRIMARY KEY(Id)
)
ENGINE = InnoDB;