CREATE DATABASE IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS userInfos;

CREATE TABLE test.userInfos (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nom VARCHAR(45) NOT NULL DEFAULT '',
  Prenom VARCHAR(45) NOT NULL DEFAULT '',
  Adresse VARCHAR(255) NOT NULL DEFAULT '',
  Birthdate DATE NOT NULL,
  Phone VARCHAR(11) NOT NULL DEFAULT '',
  Mail VARCHAR(89) NOT NULL DEFAULT '',
  NumSecu VARCHAR(16) NOT NULL DEFAULT '',
  Mdp VARCHAR(255) NOT NULL DEFAULT '',
  Ad BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS waintingUser;

CREATE TABLE test.waitingUser (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Mail VARCHAR(89) NOT NULL DEFAULT '',
  Mdp VARCHAR(255) NOT NULL DEFAULT 'xxxx',
  PRIMARY KEY(Id)
) ;