CREATE DATABASE IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS userInfos;

CREATE TABLE test.userInfos (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nom VARCHAR(128) NOT NULL DEFAULT '',
  Prenom VARCHAR(128) NOT NULL DEFAULT '',
  Adresse VARCHAR(255) NOT NULL DEFAULT '',
  Birthdate DATE NOT NULL,
  Phone VARCHAR(11) NOT NULL DEFAULT '',
  Mail VARCHAR(128) NOT NULL DEFAULT '',
  NumSecu VARCHAR(16) NOT NULL DEFAULT '',
  Mdp VARCHAR(255) NOT NULL DEFAULT '',
  Ad BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY(Id)
);

INSERT INTO Test.userInfos VALUES ('','Admin', 'ad', '32 rue des hiboux;14800;Deauville','2000-02-20','0614183945','ad@admin.fr','456123987537159','﻿$2y$10$joEnEuXwzOAURwVZDcpcxOSeojPkmNQuJlih5hT7IxiEqNGdcUDgC',1);
UPDATE `test`.`userInfos` SET `Mdp` = '$2y$10$joEnEuXwzOAURwVZDcpcxOSeojPkmNQuJlih5hT7IxiEqNGdcUDgC' WHERE (`Id` = '1');

DROP TABLE IF EXISTS waitingUser;

CREATE TABLE test.waitingUser (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Mail VARCHAR(89) NOT NULL DEFAULT '',
  Mdp VARCHAR(255) NOT NULL DEFAULT 'xxxx',
  PRIMARY KEY(Id)
) ;